site_name: DevOps Den
theme:
  name: material
  custom_dir: overrides

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true
  - git-revision-date-localized
repo_url: https://github.com/devops-den/articles
repo_name: devops-den/articles
edit_uri: edit/main/docs/